function [errmin,modelparameters,s_model_obj]=optsearch(s_obj,parasitics)
freq=s_obj.Frequencies;
LB=zeros(8,1);
UB=[10;10;10;100e-12;100e-12;100e-12;100e-15;100e-15];
norm_para=(parasitics-LB)./(UB-LB);
optnormpara=fmincon(@(x)opterr(s_obj,x),norm_para,[],[],[],[],LB,ones(8,1));
parasitics=LB+(UB-LB).*optnormpara;
s_intrin_obj=depara(s_obj,parasitics);
intrinsics=extractintrin(s_intrin_obj);
s_intrin_model_obj=calintrin(intrinsics,freq);
s_model_obj=addpara(s_intrin_model_obj,parasitics);
errmin=err(s_obj,s_model_obj);
modelparameters=[parasitics;intrinsics];